In [ ]:
# Question 1. Algebra
# Assume a product has info with 5 properties (weight (gram), width (cm), height
# (cm), color, price (USD)).
# (Color :1 (Red), 2 (Blue), 3 (Green), 4 (Yellow), 5(White), 7(Purple), 8(Black),
# 9(Magenta), 10(Cyan))
# A. Please input two vectors representing information of two products: A and B.
# And calculate the dot product of two vectors, the angle between two vectors
# Example:
# Please input product A ==&gt; Input : 3.5, 12, 5, 5, 10
# ==&gt; Vector of A is [3.5, 12, 5, 5, 10]
# Please input product B ==&gt; Input : 2.5, 10, 4, 5, 12
# ==&gt; Vector of B is [2.5, 10, 4, 5, 12]
# ==&gt; Dot Product is : 25 and Angle two vectors are : 15 degree
# (Note: The value is just example not exact the result)

# B. Create a random of 200 products and apply PCA to help reduce the dimensions
# of data from 5 to 4,3, and 2. Print out step by step of PCA with mean, covariance,
# eigenvalue, eigenvector and product vectors (after reduce)
# Example: call functions
# X = GenerateProducts(num = 200)
# ==&gt; List of random 200 products with 5 properties are : &lt;&lt;Output Here&gt;&gt;
# X_Reduce = PCA_DimensionReduce(X, reduce_dim = 3)
# ==&gt; Means = &lt;&lt;Output Here&gt;&gt;

# 2
# Assignment: Programming Fundamentals
# ==&gt; Cov = &lt;&lt;Output Here&gt;&gt;
# ==&gt; EigenValue = &lt;&lt;Output Here&gt;&gt;
# ==&gt; EighenVector = &lt;&lt;Output Here&gt;&gt;
# ==&gt; List of random 200 products with 3 properties are : &lt;&lt;Output Here&gt;&gt;

In [17]:
import numpy as np

In [13]:
while True:
  enter_vector = input("Please input product A with 5 properties(comma-seperated value):").split(",")
  A = np.array(enter_vector, dtype = float)
  if (len(A)!=5) or (A[3]<1) or (A[3]>10): 
    print("Error input!\n")
  else: break
print("Vector of A is: ",A)

while True:
  enter_vector = input("Please input product B with 5 properties(comma-seperated value):").split(",")
  B = np.array(enter_vector, dtype = float)
  if (len(B)!=5) or (B[3]<1) or (B[3]>10): 
    print("Error input!\n")
  else: break
print("Vector of A is: ",B)

Please input product A with 5 properties(comma-seperated value):3.5,12,5,5,10
Vector of A is:  [ 3.5 12.   5.   5.  10. ]
Please input product B with 5 properties(comma-seperated value):2.5,10,4,5,12
Vector of A is:  [ 2.5 10.   4.   5.  12. ]


In [14]:
from numpy import dot
from numpy.linalg import norm
dot = dot(A,B)
cos_sim = dot/(norm(A)*norm(B))
degree = np.degrees(np.arccos(cos_sim))
print(f"Dot Product is : {round(dot,2)} and Angle two vectors are : {round(degree,2)} degree")

Dot Product is : 293.75 and Angle two vectors are : 10.4 degree


In [47]:
import random
def GenerateProducts(num):
  return np.random.uniform(10.5, 75.5,size =(num,5))
data = GenerateProducts(200)
for i in range(200):
    data[i][3] = random.randint(1,10)
    for j in range(5):
      if j!=3:
        data[i][j] = round(data[i][j],2)
print("List 200 product with 5 properties are:")
print(data)

List 200 product with 5 properties are:
[[40.77 26.19 12.37 10.   21.51]
 [22.49 17.78 25.86 10.   45.5 ]
 [11.35 66.65 16.71  9.   51.6 ]
 [53.32 14.98 45.03 10.   19.09]
 [19.95 22.35 52.33  8.   44.09]
 [29.51 45.28 74.35  1.   67.14]
 [46.82 56.33 64.8   1.   11.03]
 [37.36 16.46 49.91  4.   32.18]
 [21.26 33.43 66.91  3.   43.08]
 [28.62 66.83 42.13  7.   55.58]
 [56.73 60.23 68.1   8.   53.54]
 [32.5  35.65 54.96  5.   31.93]
 [13.86 42.86 18.2   9.   19.87]
 [52.44 44.01 61.85  8.   12.09]
 [29.92 21.49 49.26  9.   33.34]
 [43.21 49.57 60.22  4.   45.78]
 [14.82 55.6  38.96  7.   29.81]
 [73.37 23.37 67.98  4.   36.75]
 [40.48 55.79 38.6   3.   55.14]
 [42.07 37.06 36.85  5.   43.37]
 [30.56 32.71 67.1   1.   62.38]
 [67.77 68.47 13.55  7.   14.9 ]
 [53.83 68.58 25.5   1.   40.31]
 [73.76 21.68 14.18  5.   55.11]
 [17.65 54.35 74.43  9.   70.97]
 [48.55 27.71 14.66  9.   61.93]
 [64.34 43.27 19.68  3.   33.83]
 [18.84 57.3  56.56 10.   37.67]
 [58.3  16.87 55.89  4.   16.56]
 [3

In [48]:
def PCA_DimensionReducedef(X , num_components):
    #Step1
    X_meaned = X - np.mean(X , axis = 0)
    print(f"Mean = {X_meaned}")
    #Step2
    cov_mat = np.cov(X_meaned , rowvar = False)
    print(f"Cov = {cov_mat}")
    #Step3
    eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
    print(f"Eigen values = {eigen_values}")
    print(f"Eigne vectors = {eigen_vectors}")
    #Step4
    sorted_index = np.argsort(eigen_values)[::-1]
    sorted_eigenvalue = eigen_values[sorted_index]
    sorted_eigenvectors = eigen_vectors[:,sorted_index]
    #Step5
    eigenvector_subset = sorted_eigenvectors[:,0:num_components]
    #Step6
    X_reduced = np.dot(eigenvector_subset.transpose() , X_meaned.transpose() ).transpose()
    return X_reduced
result = PCA_DimensionReducedef(data,4)
print("List of random 200 products with 4 properties are",result)
print()

result = PCA_DimensionReducedef(data,3)
print("List of random 200 products with 3 properties are",result)
print()

result = PCA_DimensionReducedef(data,2)
print("List of random 200 products with 2 properties are",result)
print()

result = PCA_DimensionReducedef(data,1)
print("List of random 200 products with 1 properties are",result)
print()


Mean = [[-1.013950e+00 -1.724855e+01 -3.001285e+01  4.355000e+00 -2.182170e+01]
 [-1.929395e+01 -2.565855e+01 -1.652285e+01  4.355000e+00  2.168300e+00]
 [-3.043395e+01  2.321145e+01 -2.567285e+01  3.355000e+00  8.268300e+00]
 [ 1.153605e+01 -2.845855e+01  2.647150e+00  4.355000e+00 -2.424170e+01]
 [-2.183395e+01 -2.108855e+01  9.947150e+00  2.355000e+00  7.583000e-01]
 [-1.227395e+01  1.841450e+00  3.196715e+01 -4.645000e+00  2.380830e+01]
 [ 5.036050e+00  1.289145e+01  2.241715e+01 -4.645000e+00 -3.230170e+01]
 [-4.423950e+00 -2.697855e+01  7.527150e+00 -1.645000e+00 -1.115170e+01]
 [-2.052395e+01 -1.000855e+01  2.452715e+01 -2.645000e+00 -2.517000e-01]
 [-1.316395e+01  2.339145e+01 -2.528500e-01  1.355000e+00  1.224830e+01]
 [ 1.494605e+01  1.679145e+01  2.571715e+01  2.355000e+00  1.020830e+01]
 [-9.283950e+00 -7.788550e+00  1.257715e+01 -6.450000e-01 -1.140170e+01]
 [-2.792395e+01 -5.785500e-01 -2.418285e+01  3.355000e+00 -2.346170e+01]
 [ 1.065605e+01  5.714500e-01  1.946715e+01 